sudo: false

language: cpp

compiler:
    - clang

cache:
    apt: true
    packages: true
    directories:
        - travis_build

addons:
    apt:
        packages:
            - g++-multilib

env:
    - CONFIGURATION=debug_x64
    - CONFIGURATION=debug_js
    - CONFIGURATION=release_x64
    - CONFIGURATION=release_js

install:
    - bash install-travis.sh

before_script:
    - travis_build/premake5 gmake

script:
    - make -C build config=$CONFIGURATION
    - bin/$CONFIGURATION/test

