sudo: false

language: cpp

compiler:
    - clang

cache:
    apt: true
    packages: true
    directories:
        - travis_build

addons:
    apt:
        packages:
            - g++-multilib

env:
    - CONFIGURATION=debug
    - CONFIGURATION=release

matrix:
    include:
        - script:
            - source travis_build/emsdk/emsdk_env.sh
            - make -C build config=${CONFIGURATION}_js
        - script:
            - make -C build config=${CONFIGURATION}_x64
            - bin/$CONFIGURATION/test

install:
    - bash install-travis.sh

before_script:
    - travis_build/premake5 gmake

