sudo: false

language: cpp

compiler:
    - clang

cache:
    apt: true
    packages: true
    directories:
        - travis_build

addons:
    apt:
        packages:
            - g++-multilib

env:
    - CONFIG=debug
    - CONFIG=release
    - ARCH=x64
    - ARCH=js

install:
    - bash travis-install.sh

before_script:
    - travis_build/premake5 gmake

script: bash travis-test.sh

